on: [push]
jobs:
  ci:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: cargo run -- --help #actually using this won't work in github's environment I guess
      - run: cargo doc
      - run: cargo build --release
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: target/release/execution_policy_exception
